#%RAML 1.0 NamedExample
{
  "accountNumber": 123456789,
  "address": [
    {
      "typeOfAddress": "Home",
      "city": "Albany",
      "country": "USA",
      "zip": 12866
    },
    {
      "typeOfAddress": "Work",
      "city": "Saratoga",
      "country": "US",
      "zip": 12866
    }
  ]
}